version: "3.9"

services:
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rfantibody-backend
    ports:
      - "2782:2782"
    environment:
      - ALLOW_ORIGINS=http://localhost:2239
      - JOBS_ROOT=/data/jobs
      - RFANTIBODY_IMAGE=rfantibody:latest
      - RF_WEIGHTS_HOST=./third_party/RFantibody/weights
      - HOST_DATA_DIR=${PWD}/data
      - HOST_WEIGHTS_DIR=${PWD}/third_party/RFantibody/weights
      - HOST_CODE_DIR=${PWD}/third_party/RFantibody
    volumes:
      - ./backend:/app
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "mkdir -p \"${JOBS_ROOT:-/data/jobs}\" &&
            uvicorn main:app --host 0.0.0.0 --port 2782 --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rfantibody-frontend
    ports:
      - "2239:2239"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  rfantibody:
    build:
      context: ./third_party/RFantibody
      dockerfile: Dockerfile
    image: rfantibody:latest
    profiles: ["builder"]