version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rfantibody-backend
    ports:
      - "2782:2782"
    environment:
      - ALLOW_ORIGINS=http://localhost:2239
    volumes:
      - ./backend:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: all         # 또는 1
              capabilities: ["gpu"]
              
              device_ids: ["0"]


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rfantibody-frontend
    ports:
      - "2239:2239"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
